"""Add payment fields

Revision ID: 85b5b6418e0f
Revises: b5b17a80f936
Create Date: 2024-11-27 04:58:29.922353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b5b6418e0f'
down_revision = 'b5b17a80f936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('late_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('days_overdue', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('reference')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('days_overdue')
        batch_op.drop_column('late_fee')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
