"""Add payment verification fields

Revision ID: e511b84f656f
Revises: 85b5b6418e0f
Create Date: 2024-11-27 05:11:23.696082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e511b84f656f'
down_revision = '85b5b6418e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_payment_verifier', 'user', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_verifier', type_='foreignkey')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('verification_date')

    # ### end Alembic commands ###
